// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package robotMain;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainleftMotor1;
    public static SpeedController driveTrainleftMotor2;
    public static SpeedController driveTrainleftMotor3;
    public static SpeedController driveTrainrightMotor4;
    public static SpeedController driveTrainrightMotor5;
    public static SpeedController driveTrainrightMotor6;
    public static DoubleSolenoid driveTrainshifter;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainleftMotor1 = new Talon(1);
        LiveWindow.addActuator("DriveTrain", "leftMotor1", (Talon) driveTrainleftMotor1);
        
        driveTrainleftMotor2 = new Talon(2);
        LiveWindow.addActuator("DriveTrain", "leftMotor2", (Talon) driveTrainleftMotor2);
        
        driveTrainleftMotor3 = new Talon(3);
        LiveWindow.addActuator("DriveTrain", "leftMotor3", (Talon) driveTrainleftMotor3);
        
        driveTrainrightMotor4 = new Talon(4);
        LiveWindow.addActuator("DriveTrain", "rightMotor4", (Talon) driveTrainrightMotor4);
        
        driveTrainrightMotor5 = new Talon(5);
        LiveWindow.addActuator("DriveTrain", "rightMotor5", (Talon) driveTrainrightMotor5);
        
        driveTrainrightMotor6 = new Talon(6);
        LiveWindow.addActuator("DriveTrain", "rightMotor6", (Talon) driveTrainrightMotor6);
        
        driveTrainshifter = new DoubleSolenoid(0, 0, 1);      
        LiveWindow.addActuator("DriveTrain", "shifter", driveTrainshifter);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
